// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/kest-labs/kest/api/internal/app"
	"github.com/kest-labs/kest/api/internal/infra/config"
	"github.com/kest-labs/kest/api/internal/infra/database"
	"github.com/kest-labs/kest/api/internal/infra/email"
	"github.com/kest-labs/kest/api/internal/infra/events"
	"github.com/kest-labs/kest/api/internal/infra/jwt"
	"github.com/kest-labs/kest/api/internal/infra/migration"
	"github.com/kest-labs/kest/api/internal/modules/apispec"
	"github.com/kest-labs/kest/api/internal/modules/audit"
	"github.com/kest-labs/kest/api/internal/modules/category"
	"github.com/kest-labs/kest/api/internal/modules/collection"
	"github.com/kest-labs/kest/api/internal/modules/environment"
	"github.com/kest-labs/kest/api/internal/modules/example"
	"github.com/kest-labs/kest/api/internal/modules/export"
	"github.com/kest-labs/kest/api/internal/modules/flow"
	"github.com/kest-labs/kest/api/internal/modules/history"
	"github.com/kest-labs/kest/api/internal/modules/importer"
	"github.com/kest-labs/kest/api/internal/modules/member"
	"github.com/kest-labs/kest/api/internal/modules/permission"
	"github.com/kest-labs/kest/api/internal/modules/project"
	"github.com/kest-labs/kest/api/internal/modules/projectinvite"
	"github.com/kest-labs/kest/api/internal/modules/request"
	"github.com/kest-labs/kest/api/internal/modules/run"
	"github.com/kest-labs/kest/api/internal/modules/runner"
	"github.com/kest-labs/kest/api/internal/modules/system"
	"github.com/kest-labs/kest/api/internal/modules/testcase"
	"github.com/kest-labs/kest/api/internal/modules/testrunner"
	"github.com/kest-labs/kest/api/internal/modules/user"
)

// Injectors from wire.go:

// InitApplication initializes the entire application with all dependencies.
// This is the single entry point for Wire DI.
func InitApplication() (*app.Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	service := jwt.NewService(configConfig)
	emailService := email.NewService(configConfig)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	userRepository := user.NewRepository(db)
	userService := user.NewService(userRepository, service, eventBus)
	handler := user.NewHandler(userService)
	memberRepository := member.NewRepository(db)
	memberService := member.NewService(memberRepository)
	memberHandler := member.NewHandler(memberService)
	permissionRepository := permission.NewRepository(db)
	permissionService := permission.NewService(permissionRepository)
	permissionHandler := permission.NewHandler(permissionService)
	auditRepository := audit.NewRepository(db)
	auditHandler := audit.NewHandler(auditRepository)
	projectRepository := project.NewRepository(db)
	projectService := project.NewService(projectRepository, memberService)
	projectHandler := project.NewHandler(projectService, memberService)
	projectinviteRepository := projectinvite.NewRepository(db)
	projectinviteService := projectinvite.NewService(projectinviteRepository)
	projectinviteHandler := projectinvite.NewHandler(projectinviteService, memberService)
	collectionRepository := collection.NewRepository(db)
	collectionService := collection.NewService(collectionRepository)
	collectionHandler := collection.NewHandler(collectionService, memberService)
	requestRepository := request.NewRepository(db)
	requestService := request.NewService(requestRepository, collectionRepository)
	requestHandler := request.NewHandler(requestService, memberService)
	exampleRepository := example.NewRepository(db)
	exampleService := example.NewService(exampleRepository)
	exampleHandler := example.NewHandler(exampleService)
	runnerRunner := runner.New()
	runHandler := run.NewHandler(requestService, memberService, runnerRunner)
	historyRepository := history.NewRepository(db)
	historyService := history.NewService(historyRepository)
	historyHandler := history.NewHandler(historyService, memberService)
	exportService := export.NewService(collectionService, requestService)
	exportHandler := export.NewHandler(exportService)
	importerService := importer.NewService(collectionService, requestService)
	importerHandler := importer.NewHandler(importerService)
	apispecRepository := apispec.NewRepository(db)
	apispecService := apispec.NewService(apispecRepository)
	testcaseRepository := testcase.NewRepository(db)
	apispecHandler := provideAPISpecHandler(apispecService, memberService, testcaseRepository)
	categoryRepository := category.NewRepository(db)
	categoryService := category.NewService(categoryRepository)
	categoryHandler := category.NewHandler(categoryService, memberService)
	environmentRepository := environment.NewRepository(db)
	environmentService := environment.NewService(environmentRepository)
	environmentHandler := environment.NewHandler(environmentService, memberService)
	flowRepository := flow.NewRepository(db)
	flowService := flow.NewService(flowRepository)
	flowHandler := flow.NewHandler(flowService, memberService)
	executor := testrunner.NewExecutor()
	testcaseService := testcase.NewService(testcaseRepository, apispecRepository, environmentRepository, executor)
	testcaseHandler := testcase.NewHandler(testcaseService, memberService)
	systemHandler := system.NewHandler()
	handlers := &app.Handlers{
		User:          handler,
		Member:        memberHandler,
		Permission:    permissionHandler,
		Audit:         auditHandler,
		Project:       projectHandler,
		ProjectInvite: projectinviteHandler,
		Collection:    collectionHandler,
		Request:       requestHandler,
		Example:       exampleHandler,
		Run:           runHandler,
		History:       historyHandler,
		Export:        exportHandler,
		Importer:      importerHandler,
		APISpec:       apispecHandler,
		Category:      categoryHandler,
		Environment:   environmentHandler,
		Flow:          flowHandler,
		TestCase:      testcaseHandler,
		System:        systemHandler,
	}
	application := &app.Application{
		Config:       configConfig,
		DB:           db,
		JWTService:   service,
		EmailService: emailService,
		EventBus:     eventBus,
		Migrator:     migrator,
		Handlers:     handlers,
	}
	return application, nil
}
