# .goreleaser.yaml
version: 2

project_name: kest

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: kest
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
