run:
  timeout: 5m
  tests: true
  build-tags: []

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - unconvert

linters-settings:
  govet:
    disable:
      - fieldalignment
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/kest-labs/kest/api

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - govet

    - path: tests/
      linters:
        - govet

  max-issues-per-linter: 50
  max-same-issues: 5
